name: Testing build

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - develop
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install unzip

      - name: Unzip Archive
        run: |
          unzip bluejay-ci-23.zip
          tar -xzvf bluejay-23.tar.gz

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: stylesuxx/action-gh-release@v0.31.0
        with:
          files: ./bluejay-23/*.hex
          token: ${{ secrets.ACCESS_TOKEN }}
          prerelease: true
          sequential_upload: true
          print_debug: true
