name: Comment Artifact Link

on:
  workflow_run:
    workflows: [Build Firmware]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: 'Comment Artifact link'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });

            console.log(context.payload.workflow_run);

            console.log(allArtifacts.data.artifacts[0]);

            const archiveUrl = allArtifacts.data.artifacts[0].archive_download_url
            console.log(archiveUrl);

            const pullRequestId = context.payload.workflow_run.pull_requests[0].number;
            console.log(pullRequestId)

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequestId,
              body: `[Download artifact](${archiveUrl})`
            });