name: Comment Artifact Link

on:
  workflow_run:
    workflows: [Build Firmware]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context);

            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });

            const archiveUrl = allArtifacts.data.artifacts[0].archive_download_url
            console.log(archiveUrl);

            const pullRequest = context.payload.workflow_run.pull_requests[0];
            console.log(pullRequest)

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: `[Download artifact](${archiveUrl})`
            });